export const get = () => ({ status: 200, body: "itzjustalan.in" })
export const put = () => ({ status: 200, body: "itzjustalan.in" })
export const post = () => ({ status: 200, body: "itzjustalan.in" })
export const patch = () => ({ status: 200, body: "itzjustalan.in" })
export const del = () => ({ status: 200, body: "itzjustalan.in" })
